import {useMemo,useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {Archive,ArrowLeft,ArrowUpRight,GitCompare,GitFork,History,RotateCcw,Split} from 'lucide-react';import {PageTitle,Status} from '../components/common';import {useAppStore} from '../store/useAppStore';import {derivationsOf} from '../lib/derivation';
export function Versions(){const {id}=useParams(),nav=useNavigate(),store=useAppStore(),w=store.workflows.find(x=>x.id===id);if(!w)return <div className="page"><button className="back-link" onClick={()=>nav('/workflows')}><ArrowLeft/>返回流程管理</button><Empty2/></div>;const all=[...w.versions].sort((a,b)=>b.version-a.version);return <VersionsBody key={w.id} w={w} all={all} nav={nav}/>}
function Empty2(){return <div className="empty"><div>⌁</div><b>流程不存在</b><p>可能已被移除，请返回流程列表。</p></div>}
function VersionsBody({w,all,nav}:{w:any;all:any[];nav:any}){const ws=useAppStore(s=>s.workflows);const [left,setLeft]=useState(all.at(-1)?.version||0),[right,setRight]=useState(all[0]?.version||w.version);const a=all.find((v:any)=>v.version===left),b=all.find((v:any)=>v.version===right);const source=w.derivedFrom?ws.find((x:any)=>x.id===w.derivedFrom.workflowId):undefined;const siblings=derivationsOf(ws,w.id);
 const diff=useMemo(()=>{if(!a||!b)return {added:[],removed:[],changed:[]};return {added:b.nodes.filter((n:any)=>!a.nodes.some((x:any)=>x.id===n.id)),removed:a.nodes.filter((n:any)=>!b.nodes.some((x:any)=>x.id===n.id)),changed:b.nodes.filter((n:any)=>{const old=a.nodes.find((x:any)=>x.id===n.id);return old&&JSON.stringify(old.data.config)!==JSON.stringify(n.data.config)})}},[a,b]);
 const restore=()=>{if(!a)return;useAppStore.getState().setCurrent(w.id);useAppStore.getState().restore(left);nav(`/workflows/${w.id}`)};
 return <div className="page versions-page"><button className="back-link" onClick={()=>nav(`/workflows/${w.id}`)}><ArrowLeft/>返回编辑器</button>
 <PageTitle eyebrow="流程版本" title="Version History" desc={`${w.name} · 查看发布记录、比较结构差异或恢复历史版本。`}/>
 <LineagePanel w={w} source={source} siblings={siblings} nav={nav}/>
 <div className="version-layout"><aside className="panel version-list"><h3><History/>版本记录</h3>{all.length?all.map((v:any,i:number)=><button key={v.version} className={v.version===right?'active':''} onClick={()=>setRight(v.version)}><span><b>v{v.version}</b>{i===0&&<em>当前</em>}</span><small>{v.createdAt}</small><p>{v.note}</p></button>):<div className="version-empty">该流程尚未发布，暂无版本记录。<br/>副本从草稿 v0 开始，不携带源版本历史。</div>}</aside>
 <section className="panel compare" data-testid="version-compare"><div className="compare-head"><div><GitCompare/><h2>版本对比</h2></div><button className="secondary" data-testid="restore-version" disabled={!a} onClick={restore}><RotateCcw/>恢复 v{left} 为草稿</button></div>
 {a&&b?<><div className="compare-select"><label>基准版本<select value={left} onChange={e=>setLeft(Number(e.target.value))}>{all.map((v:any)=><option key={v.version} value={v.version}>v{v.version} · {v.createdAt}</option>)}</select></label><span>→</span><label>比较版本<select value={right} onChange={e=>setRight(Number(e.target.value))}>{all.map((v:any)=><option key={v.version} value={v.version}>v{v.version} · {v.createdAt}</option>)}</select></label></div>
 <div className="diff-summary"><article><small>新增节点</small><b>{diff.added.length}</b></article><article><small>删除节点</small><b>{diff.removed.length}</b></article><article><small>配置变化</small><b>{diff.changed.length}</b></article><article><small>连线变化</small><b>{Math.abs(b.edges.length-a.edges.length)}</b></article></div>
 <div className="diff-list"><h3>变更明细</h3>{diff.added.map((n:any)=><div key={n.id} className="diff added"><span>＋ 新增</span><b>{n.data.label}</b><small>{n.type} 节点</small></div>)}{diff.removed.map((n:any)=><div key={n.id} className="diff removed"><span>− 删除</span><b>{n.data.label}</b><small>{n.type} 节点</small></div>)}{diff.changed.map((n:any)=><div key={n.id} className="diff changed"><span>~ 配置</span><b>{n.data.label}</b><small>节点配置已更新</small></div>)}{!diff.added.length&&!diff.removed.length&&!diff.changed.length&&<div className="empty-diff">这两个版本的节点结构一致</div>}<div className="release-note"><small>发布说明</small><p>{b.note}</p></div></div></>:<div className="empty-diff">草稿 v0 没有可比较的历史版本；发布后这里会出现版本记录。</div>}
 </section></div></div>}
function LineagePanel({w,source,siblings,nav}:{w:any;source:any;siblings:any[];nav:any}){const d=w.derivedFrom;
 const open=(id:string)=>{useAppStore.getState().setCurrent(id);nav(`/workflows/${id}/versions`)};
 if(d)return <section className="panel lineage" data-testid="lineage-panel"><div className="lineage-head"><GitFork/><h2>派生溯源</h2><span className="lineage-tag">副本 · 草稿起版 v0</span></div>
 <div className="lineage-chain"><div className="lineage-node self"><small>当前副本</small><b>{w.name}</b><Status value={w.status}/><small>v{w.version} · {d.derivedAt} 派生</small></div><span className="lineage-arrow">←</span><button className={'lineage-node src'+(source?'':' missing')} onClick={()=>source&&open(source.id)}><small>来源模板{source?<> · <Status value={source.status}/></>:<em className="archived-tag">源已不在列表</em>}</small><b>{d.workflowName}{source?.status==='archived'&&<Archive/>}</b><small data-testid="lineage-origin-version">原始版本 v{d.version}{d.versionCreatedAt?` · 发布于 ${d.versionCreatedAt}`:''}</small>{source&&<span className="lineage-link">查看源版本历史 <ArrowUpRight/></span>}</button></div>
 <details className="lineage-mapping" open><summary><Split/>节点编号映射（{d.nodeMap.length} 个节点 · {d.edgeMap.length} 条连线）</summary><div className="mapping-grid"><table><thead><tr><th>源节点编号</th><th></th><th>副本节点编号</th><th>节点名称</th></tr></thead><tbody>{d.nodeMap.map((m:any)=><tr key={m.newNodeId}><td className="mono">{m.sourceNodeId}</td><td>→</td><td className="mono">{m.newNodeId}</td><td>{m.label}</td></tr>)}</tbody></table><table><thead><tr><th>源连线编号</th><th></th><th>副本连线编号</th><th>路径</th></tr></thead><tbody>{d.edgeMap.map((m:any)=><tr key={m.newEdgeId}><td className="mono">{m.sourceEdgeId}</td><td>→</td><td className="mono">{m.newEdgeId}</td><td className="mono">{m.sourceNodeId} → {m.targetNodeId}{m.label?`（${m.label}）`:''}</td></tr>)}{!d.edgeMap.length&&<tr><td colSpan={4}>该模板派生时没有连线</td></tr>}</tbody></table></div></details></section>;
 return <section className="panel lineage origin" data-testid="lineage-panel"><div className="lineage-head"><GitFork/><h2>派生关系</h2><span className="lineage-tag">原始模板</span></div>{siblings.length?<div className="sibling-list"><p>已被派生 <b data-testid="lineage-count">{siblings.length}</b> 份副本，各副本独立演进、互不影响：</p>{siblings.map((s:any)=><button key={s.id} className="sibling-row" onClick={()=>open(s.id)}><span className="derived-badge"><GitFork/>副本</span><b>{s.name}</b><span className="spacer"/><Status value={s.status}/><small>v{s.version} · 派生自本模板 v{s.derivedFrom.version}</small><ArrowUpRight/></button>)}</div>:<p className="lineage-none">该流程是原始模板，尚未派生出副本。在流程列表点击 <GitFork/> 即可派生。</p>}</section>}
