import {useMemo,useState} from 'react'; import {useNavigate} from 'react-router-dom'; import {Archive,GitFork,Plus,Search,SlidersHorizontal} from 'lucide-react'; import {Empty,PageTitle,Status} from '../components/common';import {useAppStore} from '../store/useAppStore';import {derivationCount,derivationsOf} from '../lib/derivation';
export function Workflows(){const nav=useNavigate(),ws=useAppStore(s=>s.workflows),set=useAppStore(s=>s.setCurrent),create=useAppStore(s=>s.create),derive=useAppStore(s=>s.derive),archive=useAppStore(s=>s.archive);const [q,setQ]=useState(''),[status,setStatus]=useState('all'),[domain,setDomain]=useState('all'),[sort,setSort]=useState('updated'),[origin,setOrigin]=useState('all');
 const sources=useMemo(()=>ws.filter(w=>derivationCount(ws,w.id)>0).sort((a,b)=>derivationCount(ws,b.id)-derivationCount(ws,a.id)),[ws]);
 const rows=useMemo(()=>ws.filter(w=>(w.name.toLowerCase().includes(q.toLowerCase()))&&(status==='all'||w.status===status)&&(domain==='all'||w.domain===domain)&&(origin==='all'||(origin==='derived'?!!w.derivedFrom:origin==='template'?!w.derivedFrom:w.derivedFrom?.workflowId===origin))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):b.updatedAt.localeCompare(a.updatedAt)),[ws,q,status,domain,sort,origin]);
 const open=(id:string)=>{set(id);nav('/workflows/'+id)};
 const doDerive=(id:string,e:React.MouseEvent)=>{e.stopPropagation();const newId=derive(id);nav('/workflows/'+newId)};
 const nameOf=(id:string)=>ws.find(w=>w.id===id)?.name;
 return <div className="page"><PageTitle eyebrow="流程管理" title="Workflows" desc="以模板派生可追溯副本：编号重排、来源留痕、副本从草稿 v0 独立演进。" actions={<button onClick={()=>{const id=create();nav('/workflows/'+id)}}><Plus/>新建流程</button>}/>
 <div className="toolbar panel"><div className="search"><Search/><input aria-label="搜索流程" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索流程名称"/></div>
 <select aria-label="状态筛选" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="published">已发布</option><option value="draft">草稿</option><option value="archived">已归档</option></select>
 <select aria-label="业务域筛选" value={domain} onChange={e=>setDomain(e.target.value)}><option value="all">全部业务域</option>{['财务','采购','人力资源','IT服务','法务'].map(x=><option key={x}>{x}</option>)}</select>
 <select aria-label="来源筛选" data-testid="origin-filter" value={origin} onChange={e=>setOrigin(e.target.value)}><option value="all">全部来源</option><option value="derived">仅看派生副本</option><option value="template">仅看原始模板</option>{sources.length>0&&<optgroup label="按来源模板筛选">{sources.map(w=><option key={w.id} value={w.id}>派生自：{w.name}</option>)}</optgroup>}</select>
 <span className="spacer"/><SlidersHorizontal/><select aria-label="排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">最近更新</option><option value="name">名称排序</option></select></div>
 <section className="panel workflow-table">{rows.length?<table><thead><tr><th>流程名称</th><th>业务域</th><th>状态</th><th>版本</th><th>派生</th><th>最近编辑人</th><th>更新时间</th><th>异常实例</th><th></th></tr></thead><tbody>{rows.map(w=>{const count=derivationCount(ws,w.id),src=w.derivedFrom;return <tr key={w.id} data-testid="workflow-row"><td onClick={()=>open(w.id)}><div className="name-cell"><span>⌘</span><div className="name-text"><b data-testid="workflow-name">{w.name}</b>{src&&<button className="derived-badge" data-testid="derived-badge" title={`派生自 ${src.workflowName} · 源版本 v${src.version}`} onClick={e=>{e.stopPropagation();open(src.workflowId)}}><GitFork/>派生自 {src.workflowName} · v{src.version}</button>}</div></div></td><td>{w.domain}</td><td><Status value={w.status}/></td><td>v{w.version}</td><td><button className={'derive-count'+(count?'':' empty')} data-testid="derive-count" disabled={!count} title={count?`查看从「${w.name}」派生的 ${count} 份副本`:'暂无派生副本'} onClick={e=>{e.stopPropagation();setOrigin(count?w.id:'all')}}>{count||'—'}</button></td><td>{w.editor}</td><td>{w.updatedAt}</td><td className={w.abnormalCount?'danger-text':''}>{w.abnormalCount}</td><td><button title="派生副本" className="icon-btn" data-testid="derive-button" onClick={e=>doDerive(w.id,e)}><GitFork/></button><button title="归档" className="icon-btn" onClick={e=>{e.stopPropagation();archive(w.id)}}><Archive/></button></td></tr>})}</tbody></table>:<Empty title="没有找到流程" text={origin!=='all'?'当前来源筛选下没有匹配流程，试试切换“全部来源”':'调整搜索或筛选条件后重试'}/>}</section>
 {origin!=='all'&&origin!=='derived'&&origin!=='template'&&nameOf(origin)&&<div className="origin-hint panel" data-testid="origin-hint"><GitFork/><span>正在查看从模板 <b>{nameOf(origin)}</b> 派生的 {derivationsOf(ws,origin).length} 份副本（源流程归档不影响此列表）</span><button className="secondary mini" onClick={()=>setOrigin('all')}>清除来源筛选</button></div>}
 </div>}
